### PR TITLE
add parallel,sequential & hoistSpec

### LINKED ISSUE #80: Add a way to run tests in parallel
I was thinking on adding `describePar` and `describeParOnly`. so Description is marked as parallel and during execution in `_run` we are run producers in parallel. it would be very useful in case ps-spec is used for running integration tests and some tests don't effect each other.

so if you have:
``` purs
describe "delay" do
  it "can delay for 100ms" do
    delay $ Milliseconds $ 100.0 * 1.0
  it "can delay for 200ms" do
    delay $ Milliseconds $ 100.0 * 2.0
  it "can delay for 300ms" do
    delay $ Milliseconds $ 100.0 * 3.0
  it "can delay for 400ms" do
    delay $ Milliseconds $ 100.0 * 4.0
  it "can delay for 500ms" do
    delay $ Milliseconds $ 100.0 * 5.0
```
which takes 1500 ms, you can apply  this change:
``` diff
-describe "Foo" do
+describePar "Foo" do
```
and it will take 500ms.

Main issue would be logging from tests which are executing in parallel, as you would have no way to know from which one a logged message is coming from.

### PR DESCRIPTION
**Pull request by safareli**
NOTE: It's still braking change but most of the users will not be affected as only internals are changed and general api is the same

fix #80

### CODE REVIEW

**Comment by felixmulder** [comment]
First off, cool :+1: I like that it doesn't break the existing API.

I have some concerns that are purely usability and functional in nature:

What happens when your code crashes? Do we lose all of the logging? Writer just collects right, so if it crashes, I'm assuming you wouldn't get any debug output...

**Comment by felixmulder** [comment]
Also, it would be cool to be able to not log unless the test fails :)

**Comment by safareli** [comment]
> What happens when your code crashes? Do we lose all of the logging?

in case of using WriterT over Aff, if Aff crushes due to assertion failure or anything you lose log and ps-spec will mark test as failed.

> Writer just collects right, so if it crashes, I'm assuming you wouldn't get any debug output...

yes in case of writer you lose messages, so we should mention that in docs/tests and promote use of Reader instead. nice part about hoistSpec is that users can use anything as long as it can be transformed into aff, so it's less of a responsibility of this lib. tho people want we can provide some defaults type/runner `Reader (Ref (Array String))` for example.

**Comment by safareli** [comment]
> Also, it would be cool to be able to not log unless the test fails :)

In some cases you care more about logs when test fails, for diagnostic purposes.

**Comment by felixmulder** [comment]
> > Also, it would be cool to be able to not log unless the test fails :)
> In some cases you care more about logs when test fails, for diagnostic purposes

My point exactly.

**Comment by felixmulder** [comment]
Cool - let me know when you feel this is in a reviewable state!

**Comment by safareli** [comment]
it's in reviewable state, if API looks good then i would add some more tests/docs

**Comment by safareli** [comment]
@owickstrom, @felixmulder, I've just added some docs and I it's ready for review 🎊

**Comment by safareli** [comment]
This pr should also fix #68 as users can use `Either String Unit` for `it` blocks and in the end use `hoistSpec (either throw pure)`

**Comment by safareli** [comment]
I'm working on also adding support for hooks like in hspec, which is not possible without changing the test ADT so soon will open PR with par/sec execution and hooks. most of this code will be changed so no need to review

**Comment by felixmulder** [comment]
Hi!

Thanks for keeping at this, I've been on vacation, but I'm back now. Looking forward to the next PR :)

**Pull request closed without merging**
