### PR TITLE
WIP: Implement hooks

### PR DESCRIPTION
**Pull request by felixSchl**
PR for #44 

Implement "hooks" that allow running before all, before each, after all and after each test.

#### TODO:

* [x] beforeEach
* [x] beforeAll
* [ ] afterAll
* [x] afterEach
* [ ] aroundAll
* [x] aroundEach

#### Caveats:

* The approach taken is not as composable as I would like it to be. For example, nested `beforeEach` actions do not compose. The way it is currently implemented, a `beforeEach` essentially decorates a single `it` block but does not share the same type with `it`. There _may_ be a way around this one, but I have not had a chance yet to fully explore this.
* The implementation for `beforeAll` (and later `afterAll`) is kludgy at best and requires a call to `unsafeCoerce`. It also tightly couples the runner logic with the actual spec. The only way that I see to get around this is to either extend / generalize the group ADT or build the entire Spec in Aff. I would prefer the former, but that's a larger undertaking than what I have time for at this point.

At this point, I am not sure if we should even look at merging this. The cool thing is that the DSL and external facing types have not changed and likely won't have to change if we were to re-iterate in an effort to make it more composable.

### CODE REVIEW

**Comment by felixSchl** [comment]
I made it so that every spec takes an input argument now, but the current `Spec` type simply takes unit, so we can kick it off by the runner. This at least removes the 2 similar type aliases. I am not sure as to how to unify `it` and `it1`, so that you can simply use `it` and the actual type is inferred based on context. Hspec makes use of the type families which we do not have access to to achieve this (if I am reading sources correctly).

**Comment by mostalive** [comment]
Cool :-) I'm finally updating the code that could use this, so once that compiles I'll try it out. Don't have a suggestion for how to get rid of the remaining _it1 atm, sorry.

**Comment by felixSchl** [comment]
Guys I cracked it :) Using a new type class and fun deps, we can now do this:

```purescript
runnerSpec :: ∀ e eff. Spec (RunnerEffects e) Unit
runnerSpec =
  describe "Test" $
    describe "Spec" do
      describe "Runner" do
        it "supports async" do
          res <- delay (Milliseconds 10.0) *> pure 1
          res `shouldEqual` 1

      -- here `pure 10` causes the `it` handler below to expect an `Int`
      describe "beforeEach" do
        beforeEach (pure 10) do
          it "should pass result to \"it\" (1)" \n -> do
            n `shouldEqual` 10
```

All while not breaking any API compat!

**Comment by owickstrom** [comment]
@felixschl great! Looking forward to this :)

**Comment by felixSchl** [comment]
Hey, I am not sure how to do the `beforeAll` and `afterAll` ones. Let's focus on `beforeAll` first, for arguments sake. For all `it`s under a give `beforeAll` to share the same computation, we would need to store the result of the computation in an `Avar a`. But where do we get the avar from? If we create it inside the `beforeEach` handler, it's a fresh avar for each computation. Hspec gets around this issue by building the spec tree inside the IO monad. If we did this we could create an avar at construction time and pass it down to each tests. I personally do not like this approach for various reasons: 1) the building of a spec is no longer pure, 2) re-running the tests requires re-building the spec in order to create fresh avars. I am really interested in getting your thoughts on this.

**Comment by felixSchl** [comment]
Another option would be I think to extend the `Group t` ADT or generalize the `Describe` constructor

**Comment by mostalive** [comment]
@felixSchl Great stuff :-). Is the afterEach easier to do? Maybe wrap that up first and split the beforeAll and afterAll into a separate commit? 

Even just having a 'beforeEach' would help clean up some of my code. (I finally pasted a sample in https://github.com/owickstrom/purescript-spec/issues/44 )

**Comment by felixSchl** [comment]
I've added `aroundEach` and `afterEach`. `afterEach` is pretty useless right now because things are just not as composable as they should be: `afterEach` won't have any context to work with whatsoever, rendering it useless from what I can tell. `aroundEach`, however, does receive the output from `beforeEach`, so can perform clean up actions based on that.

**Comment by felixSchl** [comment]
I added an initial implementation for `beforeAll`, but it's kludgy. I've added necessary comments to the code and updated the PR description for more information.

**Comment by owickstrom** [comment]
Sorry for coming in a little late with feedback, but anyway, here it is. :)

The argument stuff looks great! OTOH, as you mentioned in your caveats, I think should to move the effectful operations of aroundEach/aroundAll to the `Runner` module, keeping `Spec` pure. As you said, it would require extending the `Group` ADT, e.g. adding `AroundEach` and `AroundAll` constructors. It would be really nice to keep the API and spec collection (`Spec` module), and the execution of a spec (`Runner` module), separate in responsibilities, and I think we wouldn't need the unsafe coercing stuff.

If you don't have time to do this change, would you mind if I hack on it today based on your branch? I have a couple of hours on the train. :)

**Comment by felixSchl** [comment]
Yeah I'd love you to :+1: i think extending the ADT it the way to go also

**Comment by owickstrom** [comment]
Major rabbit hole dive right now, rewriting the core language to use final tagless encoding. Thus we get support for multiple parameter it functions matching the before/after values. I hope ;)

**Comment by owickstrom** [comment]
@felixSchl OK, I think most of my learnings have been summed up in https://wickstrom.tech/programming/2017/06/05/tagless-final-encoding-of-a-test-language.html, if you want to check that out. :) I could try integrating this into PureScript Spec.

**Comment by felixSchl** [comment]
I've brought the finally tagless idea to purescript https://github.com/felixSchl/purescript-spec/blob/finally/src/Test/Spec.purs so we can use that as a base for further work, should we choose to take the tagless approach. I used purescript-io because the eff constraints where getting annoying and [purescript appears to be moving away from the idea](https://github.com/purescript/purescript/issues/3080) of effect rows. Anyway, the tagless approach to this problem certainly seems better than the ADT approach so far. It would be cool, however, if we could somehow feed values from a `beforeEach` (or `beforeAll`) into a nested `beforeEach`. That would require, from what I can tell, that `beforeEach` makes it's way back into the ADT

**Comment by owickstrom** [comment]
@felixSchl Cool! I'll have a look at this when I get some time (not that often right now...). Would the switch to `purescript-io` break backwards compatibility for existing test suites?

**Comment by felixSchl** [comment]
I haven't really thought that far. To be honest this PR is still kind of stalling, I had a sudden burst of motivation to understand the tagless final approach and thought I might as well go with this :o)

**Comment by garyb** [comment]
This may be of interest: https://github.com/garyb/purescript-mote, it's an API that is just for describing test suites, but doesn't have an opinion about how to run them, etc.

I've included something in the examples that uses `-spec` to run a suite defined in the Mote DSL... but maybe you'd be interested in adopting mote as the description for tests within `-spec` itself? Then all it would need to do is implement the runners / desired interface to building the spec (since it doesn't provide `describe`, `it`, etc. terminology currently).

The reason I suggest this is Mote already supports bracketing tests for pre/post running of things for setup/cleanup. The interface is a little different than having split before/after, since it allows some resource to be generated in the `before` that is then consumed in the `after`, but if the resource was just `Unit` it could still be used to describe the steps separately perhaps.

**Comment by mostalive** [comment]
I'm playing around with Mote, and about to bring @felixSchl 's code up to date on my machine (looks like just an import list diverged) so I can have a look at that too.
Seen so far in Mote:
- 'skip' is it's own thing, orthogonal to to other things, so one can `skip` a group or a single test with one primitive, instead of `itOnly` and `describyOnly`. Not yet
- Effectful code can run in a do block in a group too, bracket appears to be optional
- I haven't yet figured out how to assign something that runs in a brackets' before: to a value and use it inside a test

**Comment by safareli** [comment]
#83 is more recent try to add hooks, review/comments would be kindly appreciated 🎊

**Comment by safareli** [comment]
Closing in favor of #83 which is released as [v4.0.0-rc1](https://github.com/purescript-spec/purescript-spec/releases/tag/v4.0.0-rc1)

would be great if people play with it and report if there is any issue

**Pull request closed without merging**
