### PR TITLE
Parenthesis missing?

### PR DESCRIPTION
**Pull request by objarni**
I believe the PureScript binding rules makes for () surrounding 1 + 1. At least that is what made my test code compile after scratching head from this error message:

```at test/Main.purs:16:9 - 16:26 (line 16, column 9 - line 16, column 26)

  Could not match type
           
    t0 Unit
           
  with type
       
    Int
       

while checking that type t0 Unit
  is at least as general as type Int
while checking that expression (shouldEqual 1) 2
  has type Int
in value declaration main

where t0 is an unknown type
```

### CODE REVIEW

**Comment by fsoikin** [comment]
This is a good catch, thank you very much for the change!

Unfortunately the CI is not working, because the `prepare-0.15` package set no longer exists.
I just fixed the CI, so could you please rebase on the latest `master`, so I can run CI on this PR? 

Thank you.

**Comment by objarni** [comment]
OK, great! I believe the branch is updated now?

**Comment by objarni** [comment]
There is no auto deploy? Can still not see any () on documentation page/tutorial.

Thanks for writing this! It really helped me get started with testing in purescript today!

**Comment by fsoikin** [comment]
I'm not really sure what's going on here. Autodeploy does exist ([here's the job](https://github.com/purescript-spec/purescript-spec/actions/runs/2841082059)), but it's GitHub Pages, not a manually written one. And it looks like I don't have access the GHPages settings for this repo, so I can't check.

I'm looking into it.

**Pull request merged**
